name: Chromatic
on:
  push:
    branches:
      - develop
      - rel-*
      - release-*
      - github-actions-*
    tags:
      - v*
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - rel-*
      - release-*
    paths:
      - app/**
      - .github/workflows/chromatic.yml

jobs:
  chromatic:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Fetch dependency cache
        uses: actions/cache@v2
        with:
          key: electron-cache
          path: app/node_modules
      - name: Install dependencies
        working-directory: app
        run: yarn
      - name: Publish storybook
        working-directory: app
        run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: build-storybook-log
          path: app/build-storybook.log
